####################### 环境配置 #######################
spring:
  profiles:
    # dev-开发环境 test-测试环境 prod-生产环境
    active: dev
  devtools:
    restart:
      # 热部署开关
      enabled: true
####################### 日志配置 #######################
logging:
  path: /home/backendApp/logs
