# 日志配置
logging:
  path: ../logs
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.99.191.11:3306/ls_sys?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 111111
# mybatis-plus配置
mybatis-plus:
  # 扫描表实体注册别名，参考https://mp.baomidou.com/config/#typealiasespackage
  type-aliases-package: com.sand.*.entity
  # 扫描通用枚举注入，参考https://mp.baomidou.com/config/#typeenumspackage
  type-enums-package: com.sand.**.enums
  # 扫描映射文件，参考https://mp.baomidou.com/config/#mapperlocations
  mapper-locations: classpath*:/mapper/*Mapper.xml
  global-config:
    db-config:
      # 主键生成策略
      id-type: uuid
      # 逻辑删除配置，参考https://mp.baomidou.com/guide/logic-delete.html
      logic-delete-value: 1
      logic-not-delete-value: 0
#######################SSS 自定义配置 SSS#######################
sand:
  # 安全认证授权配置
  security:
    jwt:
      # 令牌密钥
      secret: k09BQnaF
      # 令牌过期时间
      expiration: 604800
#######################EEE 自定义配置 EEE#######################
server:
  port: 8888
