# 日志配置
logging:
  level:
    com.sand: debug
    org.springframework: warn
    com.baomidou.mybatisplus.: warn
# 数据源配置
sessionDb: 0
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ls_sys?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
  # redis配置
  redis:
    #  索引
    database: 1
    port: 6379
    host: 127.0.0.1
    password:
    timeout: 0
    jedis:
      pool:
        # 最大空闲连接数
        max-idle: 8
        # 最大等待时间
        max-wait: -1
        # 初始化连接数
        min-idle: 0
# mybatis-plus配置
mybatis-plus:
  # 扫描表实体注册别名，参考https://mp.baomidou.com/config/#typealiasespackage
  type-aliases-package: com.sand.*.entity
  # 扫描通用枚举注入，参考https://mp.baomidou.com/config/#typeenumspackage
  type-enums-package: com.sand.**.enums
  # 扫描映射文件，参考https://mp.baomidou.com/config/#mapperlocations
  mapper-locations: classpath*:/mapper/*Mapper.xml
  global-config:
    db-config:
      # 主键生成策略
      id-type: uuid
      # 逻辑删除配置，参考https://mp.baomidou.com/guide/logic-delete.html
      logic-delete-value: 1
      logic-not-delete-value: 0
# 安全认证授权配置
security:
  jwt:
    # 密钥
    secret: k09BQnaF
    # token有效期7天
    expiration: 604800
