####################### 启动端口 #######################
server:
  port: 8888
####################### 日志配置 #######################
logging:
  path: ./logs
#################### Spring基础配置 ####################
spring:
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ls_demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
  # 模板引擎
  thymeleaf:
    # 模板前缀
    prefix: classpath:/templates/
    # 模板后缀
    suffix: .html
    # 关闭缓存
    cache: false
  # 静态资源路径多个以逗号分隔
  resources:
    static-locations: classpath:/templates/,classpath:/static/
################### mybatis-plus配置 ###################
mybatis-plus:
  # 扫描表实体注册别名，参考https://mp.baomidou.com/config/#typealiasespackage
  type-aliases-package: com.sand.*.entity
  # 扫描通用枚举注入，参考https://mp.baomidou.com/config/#typeenumspackage
  type-enums-package: com.sand.**.enums
  # 扫描映射文件，参考https://mp.baomidou.com/config/#mapperlocations
  mapper-locations: classpath*:/mapper/*Mapper.xml
  global-config:
    db-config:
      # 主键生成策略
      id-type: uuid
      # 逻辑删除配置，参考https://mp.baomidou.com/guide/logic-delete.html
      logic-delete-value: 1
      logic-not-delete-value: 0
